package Lexer;

public enum SysYType {
    IDENFR,
    INTCON,
    STRCON,
    MAINTK, CONSTTK, INTTK, BREAKTK, CONTINUETK, IFTK, ELSETK, FORTK, RETURNTK, VOIDTK,
    GETINTTK, PRINTFTK,

    NOT, AND, OR, PLUS, MINU, MULT, DIV, MOD,
    LSS, LEQ, GRE, GEQ, EQL, NEQ, ASSIGN,
    LPARENT, RPARENT, LBRACK, RBRACK, LBRACE, RBRACE,
    SEMICN, COMMA,
}
